"""Loader for mined multi-commit rebase scenarios (#history corpus).

The companion to :mod:`realworld_loader`: where that loads single-file 3-way
conflict cases, this loads *multi-commit rebase scenarios* (a source branch of
N commits replayed onto a target, with conflicts at specific steps). These are
what actually exercise the history-aware mechanisms (conflict chains, future
probes, branch intent) against real git history.

Same clean-skip contract as the realworld loader: ``[]`` when the dir is absent
or empty, silently-tolerate-malformed (one bad file never breaks collection),
sorted by id for stable parametrization. Generated by
``scripts/mine_rebase_scenarios.py``; gitignored (CI never needs the clones).
"""

from __future__ import annotations

import json
from dataclasses import dataclass, field
from pathlib import Path

#: Root for extracted testdata (env-overridable via DATA_ROOT, matching the
#: realworld loader's contract).
import os
_DATA_ROOT = Path(os.environ.get("DATA_ROOT", Path(__file__).resolve().parents[1]))
SCENARIO_DIR = _DATA_ROOT / "extracted-testdata" / "rebase-scenarios"

#: The clone root (matches the fetch script's EXTERNAL). Used to locate a
#: dataset's clone for cargo checks.
EXTERNAL_DIR = _DATA_ROOT / "external-datasets"

#: dataset id -> clone subdir (matches the fetch script's DATASETS registry +
#: realworld_loader's map). Kept here so the test layer finds a clone without
#: importing the side-effecting fetch script.
_GIT_HISTORY_CLONE_SUBDIR = {
    "serde-history": "serde",
    "sea-orm-history": "sea-orm",
    "clap-history": "clap",
    "tokio-history": "tokio",
    "pydantic-history": "pydantic",
    "requests-history": "requests",
    "flask-history": "flask",
    "rayon-history": "rayon",
    "axum-history": "axum",
}


@dataclass(frozen=True)
class ConflictStepCase:
    """One conflicted replay step within a scenario."""

    step: int
    path: str
    replayed_commit_oid: str
    base: str
    current: str
    replayed: str
    marker_text: str


@dataclass(frozen=True)
class RebaseScenarioCase:
    """One mined multi-commit rebase scenario, ready to drive as a test."""

    id: str
    dataset: str
    source_tip_oid: str
    target_tip_oid: str
    merge_base_oid: str
    source_commits: list[dict] = field(default_factory=list)
    conflict_steps: list[ConflictStepCase] = field(default_factory=list)
    license: str = ""
    source_url: str = ""
    clone_subdir: str = ""

    @property
    def language(self) -> str:
        """The conflict files' language, inferred from the first step's path."""
        if not self.conflict_steps:
            return "unknown"
        p = self.conflict_steps[0].path
        if p.endswith(".py"):
            return "python"
        if p.endswith(".rs"):
            return "rust"
        return "unknown"


def git_history_repo_path(dataset_id: str) -> Path:
    """The clone path for a git-history dataset id.

    Raises ``KeyError`` for an unknown id (a programming error, not a runtime
    skip).
    """
    return EXTERNAL_DIR / _GIT_HISTORY_CLONE_SUBDIR[dataset_id]


def load_rebase_scenarios() -> list[RebaseScenarioCase]:
    """Load every scenario JSON in the testdata dir, or ``[]`` if none/absent.

    Sorted by id for stable parametrization. Returns only well-formed scenarios
    (skips a malformed file with a warning rather than failing collection — a
    single corrupt extracted file must not break the whole suite).
    """
    if not SCENARIO_DIR.is_dir():
        return []
    scenarios: list[RebaseScenarioCase] = []
    for f in sorted(SCENARIO_DIR.glob("*.json")):
        try:
            d = json.loads(f.read_text(encoding="utf-8"))
        except (json.JSONDecodeError, OSError):
            continue
        # Require the fields the harness needs; skip incomplete cases silently.
        required = ("source_tip_oid", "target_tip_oid", "source_commits",
                    "conflict_steps")
        if not all(k in d for k in required):
            continue
        if not d.get("conflict_steps"):
            continue  # a scenario with no conflicts exercises nothing
        steps = [
            ConflictStepCase(
                step=s.get("step", 0),
                path=s.get("path", ""),
                replayed_commit_oid=s.get("replayed_commit_oid", ""),
                base=s.get("base", ""),
                current=s.get("current", ""),
                replayed=s.get("replayed", ""),
                marker_text=s.get("marker_text", ""),
            )
            for s in d["conflict_steps"]
        ]
        scenarios.append(
            RebaseScenarioCase(
                id=d.get("id", f.stem),
                dataset=d.get("dataset", ""),
                source_tip_oid=d["source_tip_oid"],
                target_tip_oid=d["target_tip_oid"],
                merge_base_oid=d.get("merge_base_oid", ""),
                source_commits=d["source_commits"],
                conflict_steps=steps,
                license=d.get("license", ""),
                source_url=d.get("source_url", ""),
                clone_subdir=d.get("clone_subdir", ""),
            )
        )
    return scenarios


def has_rebase_scenario_data() -> bool:
    """True iff any rebase scenario has been generated (data downloaded)."""
    return bool(load_rebase_scenarios())
