"""Loader for session-mined merge-conflict test cases.

Reads JSON case files produced by ``scripts/export-session-testdata.py`` from
``extracted-testdata/sessions/``. Each file is one conflict capybase actually
faced in a rebase session, plus the model's accepted resolution and the
whole-file validation verdict — i.e. a *model-side* regression case, distinct
from the *human-oracle* cases in ``realworld_loader.py``.

Mirrors ``realworld_loader``'s inert-on-empty contract: when the data dir is
absent or empty (a fresh clone — the contents are gitignored, regenerated by
the script), :func:`load_session_cases` returns ``[]`` and the parametrized
tests in ``tests/test_session_conflicts.py`` skip cleanly.
"""

from __future__ import annotations

import json
from dataclasses import dataclass
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
_DATA_ROOT = Path(__import__("os").environ.get("DATA_ROOT", str(REPO_ROOT)))
TESTDATA_DIR = _DATA_ROOT / "extracted-testdata" / "sessions"


@dataclass(frozen=True)
class SessionCase:
    """One accepted conflict resolution projected from a capybase session.

    ``base``/``current``/``replayed`` are the verbatim 3-way sides parsed from
    the session's resolve prompt; ``marker_original`` is a reconstructed
    conflict-marked block (capybase doesn't store the original marked file —
    snapshots are post-resolution); ``accepted_resolution`` is the model's own
    output (NOT a human oracle). ``is_placeholder_resolution`` flags cases where
    the model emitted the JSON-contract placeholder verbatim (a real failure
    mode, kept for conflict-shape tests but excludable from resolution-content
    tests).
    """

    id: str
    session_id: str
    path: str
    language: str
    base: str
    current: str
    replayed: str
    marker_original: str
    accepted_resolution: str
    file_validation_passed: bool
    attempts: int
    needs_human: bool
    prompt_version: str
    model: str
    provenance: dict
    is_placeholder_resolution: bool


def load_session_cases() -> list[SessionCase]:
    """Load every JSON case in the sessions dir, or ``[]`` if none/absent.

    Sorted by id for stable parametrization. Skips malformed/incomplete files
    silently (a single corrupt file must not break collection), matching
    ``realworld_loader.load_realworld_cases``.
    """
    if not TESTDATA_DIR.is_dir():
        return []
    cases: list[SessionCase] = []
    for f in sorted(TESTDATA_DIR.glob("*.json")):
        try:
            d = json.loads(f.read_text(encoding="utf-8"))
        except (json.JSONDecodeError, OSError):
            continue
        required = (
            "current",
            "replayed",
            "marker_original",
            "accepted_resolution",
        )
        if not all(k in d for k in required):
            continue
        cases.append(
            SessionCase(
                id=d.get("id", f.stem),
                session_id=d.get("session_id", ""),
                path=d.get("path", f"{f.stem}.rs"),
                language=d.get("language", ""),
                base=d.get("base", ""),
                current=d["current"],
                replayed=d["replayed"],
                marker_original=d["marker_original"],
                accepted_resolution=d["accepted_resolution"],
                file_validation_passed=bool(d.get("file_validation_passed", False)),
                attempts=int(d.get("attempts", 0)),
                needs_human=bool(d.get("needs_human", False)),
                prompt_version=d.get("prompt_version", ""),
                model=d.get("model", ""),
                provenance=d.get("provenance", {}),
                is_placeholder_resolution=bool(d.get("is_placeholder_resolution", False)),
            )
        )
    return cases


def has_session_data() -> bool:
    """True iff any session case has been generated (data exported)."""
    return bool(load_session_cases())
