"""Tests for the comment classifier — the hard-coded comment-kind detector.

Part A2 of the deferred-comment-reconciliation MVP. The classifier takes the
spans from enumerate_comment_spans and labels each as MACHINE (build tags, lint
suppressions, compiler directives), LEGAL (license/copyright), GENERATED
(codegen markers), DOCTEST (executable doc examples), or DEFERRED (everything
else — the prose/invariant/TODO/local-prose bucket the masker hides and the
reconciler processes).

MACHINE/LEGAL/GENERATED/DOCTEST are non-deferable — preserved verbatim through
both passes. Only DEFERRED comments are masked and reconciled.
"""

from __future__ import annotations

from capybase.adapters.comment_classifier import classify_comment, CommentClass


# ---------------------------------------------------------------------------
# MACHINE — build tags, lint suppressions, compiler directives
# ---------------------------------------------------------------------------


def test_rust_doc_comment_machine_directive():
    """A Rust doc-comment-shaped directive (``//noinspection``, ``// fmt:off``)
    is MACHINE. Note: ``#[derive(Debug)]`` is an ATTRIBUTE (code, not a comment)
    — it's never passed to the classifier (enumerate_comment_spans doesn't emit
    attributes). Only comment-SHAPED machine directives are classified here."""
    assert classify_comment("//noinspection ConstantValue", "rust") == CommentClass.MACHINE
    assert classify_comment("// fmt:off", "rust") == CommentClass.MACHINE
    assert classify_comment("// clippy::all", "rust") == CommentClass.MACHINE


def test_pragma_is_machine():
    """C/C++ ``#pragma once`` is a compiler directive."""
    assert classify_comment("#pragma once", "cpp") == CommentClass.MACHINE


def test_lint_suppression_is_machine():
    """``// eslint-disable-next-line`` is a lint suppression — MACHINE."""
    assert classify_comment("// eslint-disable-next-line no-unused-vars", "javascript") == CommentClass.MACHINE


def test_type_ignore_is_machine():
    """``# type: ignore`` (mypy) is a type-checker directive — MACHINE."""
    assert classify_comment("# type: ignore", "python") == CommentClass.MACHINE


# ---------------------------------------------------------------------------
# LEGAL — license/copyright headers
# ---------------------------------------------------------------------------


def test_license_header_is_legal():
    """A license/copyright comment is LEGAL — never rewritten automatically."""
    assert classify_comment("// Copyright 2024 Acme Corp. All rights reserved.", "rust") == CommentClass.LEGAL
    assert classify_comment("// SPDX-License-Identifier: MIT", "rust") == CommentClass.LEGAL
    assert classify_comment("# Licensed under the Apache License, Version 2.0", "python") == CommentClass.LEGAL


# ---------------------------------------------------------------------------
# GENERATED — codegen markers
# ---------------------------------------------------------------------------


def test_generated_marker_is_generated():
    """``// Code generated by protoc. DO NOT EDIT.`` is GENERATED."""
    assert classify_comment("// Code generated by protoc. DO NOT EDIT.", "rust") == CommentClass.GENERATED
    assert classify_comment("// @generated", "rust") == CommentClass.GENERATED


# ---------------------------------------------------------------------------
# DOCTEST — executable doc examples
# ---------------------------------------------------------------------------


def test_python_doctest_is_doctest():
    """A Python docstring with ``>>>`` is a doctest — non-deferable (executable)."""
    assert classify_comment('""">>> foo()\n1"""', "python") == CommentClass.DOCTEST
    assert classify_comment("# >>> foo()\n# 1", "python") == CommentClass.DOCTEST


def test_rust_doc_with_code_block_is_doctest():
    """A Rust ``///`` doc comment with a fenced code block is a doctest."""
    assert classify_comment('/// ```\n/// assert_eq!(1 + 1, 2);\n/// ```', "rust") == CommentClass.DOCTEST


# ---------------------------------------------------------------------------
# DEFERRED — everything else (prose, TODO, invariant, local narration)
# ---------------------------------------------------------------------------


def test_plain_prose_comment_is_deferred():
    """An ordinary prose comment is DEFERRED — the masker hides it, the reconciler
    processes it."""
    assert classify_comment("// Retry transient errors three times.", "rust") == CommentClass.DEFERRED
    assert classify_comment("# This function computes the factorial.", "python") == CommentClass.DEFERRED


def test_todo_comment_is_deferred():
    """TODO/FIXME comments are DEFERRED (processed conservatively by the reconciler)."""
    assert classify_comment("// TODO: add error handling", "rust") == CommentClass.DEFERRED
    assert classify_comment("# FIXME: this is broken", "python") == CommentClass.DEFERRED


def test_rust_doc_comment_without_code_block_is_deferred():
    """A Rust ``///`` doc comment WITHOUT a fenced code block is DEFERRED prose
    (not a doctest)."""
    assert classify_comment("/// Returns the current count.", "rust") == CommentClass.DEFERRED


def test_invariant_comment_is_deferred():
    """A rationale/invariant comment (explains WHY, not WHAT) is DEFERRED."""
    assert classify_comment(
        "// Do not combine these writes; the storage service uses the\n"
        "// first write as a durability boundary.",
        "rust",
    ) == CommentClass.DEFERRED


# ---------------------------------------------------------------------------
# Bulk classification via classify_spans
# ---------------------------------------------------------------------------


def test_classify_spans_labels_each():
    """classify_spans takes the output of enumerate_comment_spans and labels each."""
    from capybase.adapters.string_lexer import enumerate_comment_spans
    from capybase.adapters.comment_classifier import classify_spans, ClassifiedComment

    text = (
        "// Copyright 2024 Acme.\n"           # LEGAL
        "#[derive(Debug)]\n"                   # not a comment (attribute)
        "struct Config {\n"
        "    // max retries\n"                 # DEFERRED
        "    retries: u32,\n"
        "}\n"
        "// Code generated. DO NOT EDIT.\n"    # GENERATED
    )
    spans = enumerate_comment_spans(text, "rust")
    classified = classify_spans(spans, text, "rust")
    classes = [c.cls for c in classified]
    assert CommentClass.LEGAL in classes
    assert CommentClass.GENERATED in classes
    assert CommentClass.DEFERRED in classes
