"""S28-155 — true_side_portfolio decline telemetry.

Every portfolio decline journals WHICH precondition failed: the stage
sides' availability, each side's verification outcome, and (at the
Phase-1 caller) unit-coverage skips. Before this, declines were silent
Nones — the duckdb-0077-class blind spot where a case escalated with no
journal trace of the portfolio ever evaluating. These tests pin the
event names and payloads on a stub orchestrator.
"""

from __future__ import annotations

from types import SimpleNamespace

from capybase.orchestrator import Orchestrator, _is_lockfile_path


class _RecJournal:
    def __init__(self):
        self.events: list[tuple[str, dict]] = []

    def emit(self, event, payload, **_kw):
        self.events.append((event, payload))


class _FakeGit:
    def __init__(self, stages: dict[int, str]):
        self._stages = stages
        self.repo = "/tmp/fake-repo"

    def read_stage_blob(self, path: str, stage: int) -> bytes:
        if stage not in self._stages:
            raise RuntimeError(f"no stage {stage}")
        return self._stages[stage].encode()


class _AlwaysPassVerification:
    def verify_file(self, path, language, original, units, *, repo_root=None,
                    pristine_side_texts=None, whole_text=None):
        return SimpleNamespace(passed=True, hard_failures=[],
                               resolved_text=None)


class _AlwaysFailVerification:
    def __init__(self):
        self.calls: list[str | None] = []

    def verify_file(self, path, language, original, units, *, repo_root=None,
                    pristine_side_texts=None, whole_text=None):
        self.calls.append(whole_text)
        return SimpleNamespace(passed=False, hard_failures=[
            SimpleNamespace(message="error: nope")])


class _RepairVerification:
    """The R1 shape: passes only after a coherence repair."""

    def verify_file(self, path, language, original, units, *, repo_root=None,
                    pristine_side_texts=None, whole_text=None):
        return SimpleNamespace(passed=True, hard_failures=[],
                               resolved_text=whole_text + "\n// repaired")


_LOCK = ('# This file is automatically @generated by Cargo.\nversion = 3\n'
         '\n[[package]]\nname = "axum"\nversion = "0.7.9"\n')
_CUR_LOCK = _LOCK + '[[package]]\nname = "cur-only"\nversion = "1.0.0"\n'
_REP_LOCK = _LOCK + '[[package]]\nname = "rep-only"\nversion = "2.0.0"\n'


def _units(path="Cargo.lock", n=2):
    from capybase.conflict_model import ConflictSide, ConflictUnit
    return [ConflictUnit(
        session_id="s", step_index=1, path=path, language="toml",
        unit_id=f"{path}:{i}:0", unit_kind="text_marker_block",
        base=ConflictSide(label="BASE", text=_LOCK),
        current=ConflictSide(label="CURRENT_UPSTREAM_SIDE", text=_CUR_LOCK),
        replayed=ConflictSide(label="REPLAYED_COMMIT_SIDE", text=_REP_LOCK),
        original_worktree_text=_CUR_LOCK,
        marker_span=(0, 1),
    ) for i in range(n)]


def _orch(verification, *, stages=None) -> Orchestrator:
    orch = object.__new__(Orchestrator)
    orch.resolution_engine = None
    orch.journal = _RecJournal()
    orch.step = 1
    orch.git = _FakeGit(stages if stages is not None
                        else {1: _LOCK, 2: _CUR_LOCK, 3: _REP_LOCK})
    orch.verification = verification
    orch.config = SimpleNamespace(
        future=SimpleNamespace(
            enable_true_side_asymmetry_takeover=True,
            enable_midband_subsumption_takeover=True,
            enable_lockfile_takeover=True))
    orch._write_worktree_only = lambda *a, **k: None
    return orch


def test_no_stage_sides_decline_is_journaled():
    """The first precondition: unreadable stage blobs used to be a silent
    None — the exact 0077 shape (no trace at all)."""
    orch = _orch(_AlwaysPassVerification(), stages={})
    out = orch._try_true_side_portfolio(
        "Cargo.lock", "toml", _CUR_LOCK, _units(), phase1_fast_path=True)
    assert out is None
    decl = [p for e, p in orch.journal.events
            if e == "true_side_portfolio_declined"]
    assert decl and decl[0]["reason"] == "no_stage_sides"
    assert decl[0]["phase1"] is True
    assert decl[0]["n_units"] == 2


def test_verify_declines_are_journaled_per_side():
    """Both sides' verify outcomes recorded when nothing verifies — via
    the lockfile trigger (single candidate: current)."""
    assert _is_lockfile_path("Cargo.lock")
    ver = _AlwaysFailVerification()
    orch = _orch(ver)
    out = orch._try_true_side_portfolio(
        "Cargo.lock", "toml", _CUR_LOCK, _units(), phase1_fast_path=True)
    assert out is None
    decl = [p for e, p in orch.journal.events
            if e == "true_side_portfolio_declined"]
    assert decl and decl[-1]["reason"] == "no_verifying_side"
    assert decl[-1]["side_declines"] == {"current": "verify_failed"}
    assert decl[-1]["trigger"] == "lockfile_takeover"
    assert len(ver.calls) == 1  # the single gate-determined candidate


def test_coherence_repair_decline_is_journaled():
    """R1: a side that only passes after a repair declines with its own
    reason instead of silently vanishing."""
    orch = _orch(_RepairVerification())
    out = orch._try_true_side_portfolio(
        "Cargo.lock", "toml", _CUR_LOCK, _units(), phase1_fast_path=True)
    assert out is None
    decl = [p for e, p in orch.journal.events
            if e == "true_side_portfolio_declined"]
    assert decl and decl[-1]["reason"] == "no_verifying_side"
    assert decl[-1]["side_declines"] == {"current": "coherence_repair_needed"}
