"""Sprint-20 S20.5a — lockfile generated-file takeover (Cargo.lock).

Lockfiles are @generated regeneration artifacts: the meaningful merge
happens in the manifest, and the real-world lockfile oracle is the
CURRENT side's regeneration in practice (measured on both corpus
Cargo.lock cases: 21/21 current-only pins kept, 0/38 replayed-only,
~99.7% of divergent package keys take current's block). The takeover
proposes the current pristine stage file BEFORE the per-unit cascade —
axum-0017 otherwise burns 103 LLM units for a WORKING at sim 0.625 —
through the same verify machinery as every whole-file swap; a failed
verify declines to the per-unit path unchanged.

These tests pin the wiring inside _try_true_side_portfolio's Phase-1
branch (fixtures mirror tests/test_midband_subsumption.py).
"""

from __future__ import annotations

from types import SimpleNamespace

from capybase.orchestrator import Orchestrator, _is_lockfile_path


class _RecJournal:
    def __init__(self):
        self.events = []

    def emit(self, event, payload, **kw):
        self.events.append((event, payload))


class _FakeGit:
    def __init__(self, stages: dict[int, str]):
        self._stages = stages
        self.repo = "/tmp/fake-repo"

    def read_stage_blob(self, path: str, stage: int) -> bytes:
        if stage not in self._stages:
            raise RuntimeError(f"no stage {stage}")
        return self._stages[stage].encode()


class _AlwaysPassVerification:
    def verify_file(self, path, language, original, units, *, repo_root=None, pristine_side_texts=None,
                    whole_text=None):
        return SimpleNamespace(passed=True, hard_failures=[])


class _FailVerification:
    def verify_file(self, path, language, original, units, *, repo_root=None, pristine_side_texts=None,
                    whole_text=None):
        return SimpleNamespace(passed=False, hard_failures=[])


_LOCK = '# This file is automatically @generated by Cargo.\nversion = 3\n\n[[package]]\nname = "axum"\nversion = "0.7.9"\n'
_CUR_LOCK = _LOCK + '[[package]]\nname = "cur-only"\nversion = "1.0.0"\n'
_REP_LOCK = _LOCK + '[[package]]\nname = "rep-only"\nversion = "2.0.0"\n'


def _units(path="Cargo.lock", n=2):
    from capybase.conflict_model import ConflictSide, ConflictUnit
    return [ConflictUnit(
        session_id="s", step_index=1, path=path, language="toml",
        unit_id=f"{path}:{i}:0", unit_kind="text_marker_block",
        base=ConflictSide(label="BASE", text=_LOCK),
        current=ConflictSide(label="CURRENT_UPSTREAM_SIDE", text=_CUR_LOCK),
        replayed=ConflictSide(label="REPLAYED_COMMIT_SIDE", text=_REP_LOCK),
        original_worktree_text=_CUR_LOCK,
        marker_span=(0, 1),
    ) for i in range(n)]


def _orch(verification=None, *, flag=True) -> Orchestrator:
    orch = object.__new__(Orchestrator)
    orch.resolution_engine = None
    orch.journal = _RecJournal()
    orch.step = 1
    orch.git = _FakeGit({1: _LOCK, 2: _CUR_LOCK, 3: _REP_LOCK})
    orch.verification = verification or _AlwaysPassVerification()
    orch.config = SimpleNamespace(
        future=SimpleNamespace(
            enable_true_side_asymmetry_takeover=True,
            enable_midband_subsumption_takeover=True,
            enable_lockfile_takeover=flag),
    )
    orch._write_worktree_only = lambda *a, **k: None
    return orch


def test_is_lockfile_path():
    assert _is_lockfile_path("Cargo.lock")
    assert _is_lockfile_path("crate/Cargo.lock")
    assert _is_lockfile_path("cargo.lock")
    assert not _is_lockfile_path("src/lib.rs")
    assert not _is_lockfile_path("docs/Cargo.lock.md")
    assert not _is_lockfile_path("")


def test_lockfile_takes_current_side():
    orch = _orch()
    out = orch._try_true_side_portfolio(
        "Cargo.lock", "toml", _CUR_LOCK, _units(), phase1_fast_path=True)
    assert out is not None
    accepted, buffer, _validation = out
    assert buffer == _CUR_LOCK  # current's pristine regeneration
    gates = [e for e in orch.journal.events
             if e[0] == "lockfile_takeover_gate"]
    assert gates and gates[0][1]["winner"] == "current"
    assert gates[0][1]["n_units"] == 2


def test_lockfile_takeover_declines_when_flag_off():
    orch = _orch(flag=False)
    out = orch._try_true_side_portfolio(
        "Cargo.lock", "toml", _CUR_LOCK, _units(), phase1_fast_path=True)
    # Falls through to the ordinary Phase-1 gates (churn-shape dependent);
    # with these small fixtures nothing fires, and no lockfile event fires.
    assert not [e for e in orch.journal.events
                if e[0] == "lockfile_takeover_gate"]


def test_lockfile_takeover_declines_when_verify_fails():
    orch = _orch(_FailVerification())
    out = orch._try_true_side_portfolio(
        "Cargo.lock", "toml", _CUR_LOCK, _units(), phase1_fast_path=True)
    assert out is None  # cascade proceeds unchanged


def test_non_lockfile_path_untouched():
    orch = _orch()
    out = orch._try_true_side_portfolio(
        "src/lib.rs", "rust", _CUR_LOCK, _units(path="src/lib.rs"),
        phase1_fast_path=True)
    assert not [e for e in orch.journal.events
                if e[0] == "lockfile_takeover_gate"]
    # whatever the ordinary gates decided, the lockfile branch never fired


def test_lockfile_takeover_not_triggered_mid_phase2():
    # The mid-Phase-2 call sites pass phase1_fast_path=False — the lockfile
    # branch must not re-fire there (the pre-cascade call already had its
    # chance; a re-fire would swap mid-repair buffers).
    orch = _orch()
    orch._try_true_side_portfolio(
        "Cargo.lock", "toml", _CUR_LOCK, _units(), phase1_fast_path=False)
    assert not [e for e in orch.journal.events
                if e[0] == "lockfile_takeover_gate"]
