"""Session-mined conflict cases — the model-side regression set.

Drives conflicts capybase actually faced during a real rebase (projected from
session journals by ``scripts/export-session-testdata.py`` into
``extracted-testdata/sessions/``) through the verifier, using the MODEL'S OWN
accepted resolution. This is the complement to ``test_realworld_conflicts.py``:

- **realworld set** — human merge (M) is the oracle; "does capybase accept M?"
- **session set**   — the model's merge is the subject; "does capybase still
  resolve what it once resolved, and do the hooks still fire on this conflict?"

The cases are messier than the curated rows (multi-unit files, units that went
through repair loops, even a unit where the model emitted the JSON-contract
placeholder verbatim). That mess is the point: it's the distribution capybase
sees in the wild.

Like the realworld set, the data is gitignored (regenerated by the script), so a
fresh clone has NO data and this module SKIPS entirely. To populate it:

    python scripts/export-session-testdata.py --session <repo>/.rebase-agent/sessions/<id>

Oracle policy mirrors the realworld module: we assert only infrastructure
invariants (the floor ENGAGED, markers parse) and RECORD verdicts honestly — a
session resolution that doesn't compile under our floor is an informative flag
(notably Rust: standalone files can't resolve ``crate::`` paths, so a Rust
session case that fails here is expected and not a regression).
"""

from __future__ import annotations

import pytest

from capybase.adapters.parsers import (
    contains_markers,
    parse_marker_blocks,
)
from capybase.verification import ValidationConfig, VerificationEngine

from tests.session_loader import (
    SessionCase,
    load_session_cases,
)

# Module-level skip: no exported session data → the whole set is inert. Names
# the script so a contributor knows how to populate it.
pytestmark = pytest.mark.skipif(
    not load_session_cases(),
    reason=(
        "no session test data exported; run "
        "scripts/export-session-testdata.py --session <session-dir>"
    ),
)

CASES = load_session_cases()


@pytest.mark.parametrize("case", CASES, ids=[c.id for c in CASES])
def test_session_marker_parses(case: SessionCase):
    """The reconstructed marker block parses to exactly one conflict block.

    Guards the collector's ``marker_original`` reconstruction (current + replayed
    [+ diff3 base]) — a malformed block would ``ValueError`` here.
    """
    blocks = parse_marker_blocks(case.marker_original)
    assert len(blocks) >= 1, f"{case.id}: no conflict blocks in marker_original"


@pytest.mark.parametrize("case", CASES, ids=[c.id for c in CASES])
def test_session_sides_round_trip(case: SessionCase):
    """The marker block's parsed sides equal the stored current/replayed/base.

    Guards the collector's prompt-section parser: the sides stored as top-level
    fields must be recoverable by parsing the reconstructed marker block. A
    mismatch means the prompt parser mis-extracted a side.
    """
    blocks = parse_marker_blocks(case.marker_original)
    assert blocks, f"{case.id}: marker did not parse"
    block = blocks[0]
    assert block.current_text == case.current, (
        f"{case.id}: current side mismatch — prompt parser mis-extracted it"
    )
    assert block.replayed_text == case.replayed, (
        f"{case.id}: replayed side mismatch — prompt parser mis-extracted it"
    )
    # base is carried in a diff3 ||||||| section when non-empty.
    if case.base.strip():
        assert block.base_text == case.base, (
            f"{case.id}: base side mismatch — prompt parser mis-extracted it"
        )


@pytest.mark.parametrize("case", CASES, ids=[c.id for c in CASES])
def test_session_resolution_is_marker_free(case: SessionCase):
    """The model's accepted resolution has no leftover conflict markers.

    A leaked marker would mean the splicer or the model produced a half-merge.
    Placeholder resolutions (the model echoing the JSON-contract stub) are still
    marker-free by construction, so this holds for them too.
    """
    assert not contains_markers(case.accepted_resolution), (
        f"{case.id}: accepted resolution still contains conflict markers"
    )


@pytest.mark.parametrize("case", CASES, ids=[c.id for c in CASES])
def test_session_python_resolution_floor_engages(case: SessionCase, tmp_path):
    """Python: splice the model resolution into the marker block and run py_compile.

    We don't have the whole original file (capybase doesn't store the pre-
    conflict marked file), so the "file" under test is the marker block itself
    with the resolution spliced in. This isn't a compile-truth oracle (a single
    block out of context rarely compiles) — we assert only that the floor
    ENGAGED (``syntax_checked is True``), guarding the verifier wiring. The
    verdict is recorded honestly.
    """
    if case.language != "python":
        pytest.skip("Python-only splice-floor test (Rust has no crate context here)")
    blocks = parse_marker_blocks(case.marker_original)
    assert blocks, f"{case.id}: marker did not parse"
    spans_and_texts = [(blocks[0].span(), case.accepted_resolution)]
    eng = VerificationEngine.default(ValidationConfig())
    res = eng.verify_file(
        case.path, case.language, case.marker_original, spans_and_texts,
        repo_root=str(tmp_path),
    )
    assert res.features.get("syntax_checked") is True, (
        f"{case.id}: py_compile floor did not engage (syntax_checked=False) — "
        f"infrastructure regression. features={res.features}"
    )


@pytest.mark.parametrize("case", CASES, ids=[c.id for c in CASES])
def test_session_placeholder_flag_is_honest(case: SessionCase):
    """``is_placeholder_resolution`` is set iff the resolution is the stub.

    A bidirectional guard on the collector's placeholder detection: if the flag
    is True the stub must actually be present, and vice-versa. This keeps the
    flag trustworthy for downstream filtering (resolution-content tests exclude
    placeholders; conflict-shape tests keep them).

    Note this does NOT assert a placeholder can't also have
    ``file_validation_passed`` — it can: ``file_validation_passed`` is a
    FILE-level verdict attributed to the path, and a sub-unit whose own
    accepted candidate was the stub can still belong to a file that validated
    overall (the whole-file repair path settles the conflict on another unit).
    That mismatch is real session behavior, not a projection bug.
    """
    stub = "<merged replacement text>"
    if case.is_placeholder_resolution:
        assert stub in case.accepted_resolution, (
            f"{case.id}: is_placeholder_resolution=True but the stub is absent"
        )
    else:
        assert stub not in case.accepted_resolution, (
            f"{case.id}: is_placeholder_resolution=False but the stub is present"
        )
