"""Tracked-state audit: no corpus repository sources or derived test cases.

The corpus pipeline is scripts-only: scripts/fetch_mergeconflict_datasets.py
downloads archives into downloads/, extracts into external-datasets/, and
materializes usable cases into extracted-testdata/ — all gitignored landing
dirs whose only tracked content is an ignore-everything .gitignore so the
empty dirs exist on a fresh clone. Nothing derived from external repos is
ever committed, even in modified form; hooks/pre-commit (corpus-source
guard) enforces this at commit time. These tests audit the tracked state
itself, so the invariant holds even when commits bypass the hook
(`--no-verify`, tooling that doesn't install hooks).

Derived-but-legitimate content lives in scripts/loaders and in SYNTHETIC
fixtures authored in-repo (tests/fixtures/regression/*.json,
fixtures/specs/*.json) — those carry no external provenance, which is
asserted too.
"""

from __future__ import annotations

import subprocess
from pathlib import Path

import pytest

_REPO = Path(__file__).resolve().parent.parent

DATASET_DIRS = ("downloads", "external-datasets", "extracted-testdata")

# Derived conflict cases would land as patches/diffs; fetched corpora as
# archives. None of these formats may ever be tracked.
BANNED_SUFFIXES = (
    ".patch", ".diff", ".tar", ".tar.gz", ".tgz", ".zip", ".7z",
    ".bz2", ".xz", ".zst", ".jar", ".whl", ".pyc",
)

# corpus/ is pipeline CODE (loaders, runners, docs) — data never lives there.
CORPUS_ALLOWED_SUFFIXES = {".py", ".md", ".sh", ".toml"}


def _tracked() -> list[str]:
    return subprocess.run(
        ["git", "-C", str(_REPO), "ls-files", "-z"],
        capture_output=True, text=False, check=True,
    ).stdout.decode().split("\0")


def test_dataset_dirs_track_only_their_gitignore_placeholder():
    for d in DATASET_DIRS:
        tracked = [f for f in _tracked() if f == d or f.startswith(d + "/")]
        assert tracked == [f"{d}/.gitignore"], (
            f"{d}/ must track only its ignore-everything .gitignore "
            f"(found {tracked}) — corpus sources and derived cases are "
            "regenerated by scripts, never committed")


def test_dataset_dir_gitignores_ignore_everything():
    for d in DATASET_DIRS:
        text = (_REPO / d / ".gitignore").read_text()
        assert "*" in text and "!.gitignore" in text, (
            f"{d}/.gitignore must contain '*' + '!.gitignore' so the dir "
            "exists on a fresh clone while its generated contents stay "
            "untracked")


def test_no_archive_or_patch_files_tracked():
    offenders = [
        f for f in _tracked()
        if f.lower().endswith(BANNED_SUFFIXES)
        or f.lower().endswith(tuple(s + ".gz" for s in (".tar",)))
    ]
    assert not offenders, (
        f"archive/patch files tracked ({offenders[:5]}): fetched corpora and "
        "derived conflict cases must never enter the repo")


def test_no_tracked_file_at_or_above_the_hook_size_cap():
    cap = 2_000_000  # mirrors CORPUS_SIZE_CAP in hooks/pre-commit
    offenders = []
    for f in _tracked():
        size = (_REPO / f).stat().st_size
        if size >= cap:
            offenders.append(f"{f} ({size} bytes)")
    assert not offenders, (
        f"tracked files at/above the {cap}-byte cap ({offenders[:5]}): bulk "
        "external/archived content is banned; hooks/pre-commit enforces the "
        "same cap at stage time")


def test_corpus_dir_is_code_only():
    offenders = []
    for f in _tracked():
        if not f.startswith("corpus/"):
            continue
        suffix = Path(f).suffix
        if suffix not in CORPUS_ALLOWED_SUFFIXES:
            offenders.append(f)
    assert not offenders, (
        f"non-code files tracked under corpus/ ({offenders[:5]}): the corpus "
        "dir holds loaders/runners only; data and derived cases belong in "
        "the gitignored landing dirs")


@pytest.mark.parametrize("spec_dir", ["fixtures/specs", "tests/fixtures/regression"])
def test_in_repo_fixtures_carry_no_external_provenance(spec_dir):
    """The tracked fixture families are SYNTHETIC (authored in-repo). A URL
    or forge host inside them would be evidence of content copied or
    derived from an external repository rather than written here."""
    forbidden = ("http://", "https://", "github.com", "gitlab", "bitbucket",
                 "codeload")
    offenders = []
    for p in sorted((_REPO / spec_dir).glob("*.json")):
        text = p.read_text().lower()
        hit = next((needle for needle in forbidden if needle in text), None)
        if hit:
            offenders.append(f"{p.relative_to(_REPO)}: contains {hit!r}")
    assert not offenders, (
        "synthetic fixture specs must not carry external provenance: "
        + "; ".join(offenders))
