"""s27-78: the seeds family goes orchestrator-native.

compute_convergence_seeds derives the census-backed seeds (convergence
1080/1080, transient 499/499, generator 30/30) from a rebase's two final
states using the same GitBackend primitives production uses — no harness
required.
"""

from __future__ import annotations

from pathlib import Path

from capybase.git_backend import GitBackend
from capybase.seeds import _GEN_OUTPUT, compute_convergence_seeds

from tests.conftest import git


def _build_rebase_repo(repo: Path) -> tuple[str, str, str]:
    """base -> main (target side) / feat (source side) with one path per
    arm: converged (equal at both tips), transient (added+deleted inside
    the feat range), generated (differs, generator-named), plain (differs,
    non-generator)."""
    git(repo, "init", "-q", "-b", "main")
    (repo / "converged.txt").write_text("final content\n")
    (repo / "plain.txt").write_text("plain base\n")
    git(repo, "add", "-A")
    git(repo, "commit", "-q", "-m", "base")
    base = git(repo, "rev-parse", "HEAD").stdout.strip()

    git(repo, "checkout", "-q", "main")
    (repo / "autogenerated_settings.cpp").write_text("GENERATED v1\n")
    (repo / "plain.txt").write_text("plain main\n")
    git(repo, "add", "-A")
    git(repo, "commit", "-q", "-m", "main: v1 gen + plain")
    main_tip = git(repo, "rev-parse", "HEAD").stdout.strip()

    # feat churns converged.txt (touched -> in the log-union universe) and
    # ends it back at the main-side content: equal at both tips.
    git(repo, "checkout", "-q", "-b", "feat")
    (repo / "converged.txt").write_text("transient churn\n")
    (repo / "transient.txt").write_text("born to die\n")
    (repo / "autogenerated_settings.cpp").write_text("GENERATED v2\n")
    (repo / "plain.txt").write_text("plain feat\n")
    git(repo, "add", "-A")
    git(repo, "commit", "-q", "-m", "feat: churn + work")
    (repo / "transient.txt").unlink()
    (repo / "autogenerated_settings.cpp").write_text("GENERATED final\n")
    (repo / "converged.txt").write_text("final content\n")
    git(repo, "add", "-A")
    git(repo, "commit", "-q", "-m", "feat: cleanup + regenerate")
    feat_tip = git(repo, "rev-parse", "HEAD").stdout.strip()
    return base, main_tip, feat_tip


def test_compute_convergence_seeds_all_three_arms(repo):
    repo = Path(repo)
    base, target, source = _build_rebase_repo(repo)
    backend = GitBackend(repo)
    seeds = compute_convergence_seeds(
        backend, target_tip=target, source_tip=source, merge_base=base)

    # convergence: equal at both tips -> the shared content
    assert seeds["converged.txt"] == "final content\n"
    # transient: absent at both tips -> delete-seed
    assert seeds["transient.txt"] == ""
    # generator: differs + basename matches -> source tip verbatim
    assert seeds["autogenerated_settings.cpp"] == "GENERATED final\n"
    # plain differs, non-generator -> NOT seeded (the cascade decides)
    assert "plain.txt" not in seeds


def test_registrar_populates_and_harness_precedence(repo):
    """The orchestrator registrar fills _convergence_seeds from the rebase
    state; an already-registered dict (the eval harness) wins."""
    from capybase.orchestrator import Orchestrator

    repo = Path(repo)
    _build_rebase_repo(repo)
    # Start a real STOPPED rebase: main advances with a conflicting change
    # (feat already contains main_tip, so main must move for a conflict).
    git(repo, "checkout", "-q", "main")
    (repo / "plain.txt").write_text("plain main conflicting\n")
    git(repo, "add", "-A")
    git(repo, "commit", "-q", "-m", "main: conflict")
    git(repo, "checkout", "-q", "feat")
    git(repo, "rebase", "main", check=False)
    assert (repo / ".git").exists()  # sanity: fixture repo alive

    events = []

    class _Journal:
        def emit(self, *args, **kwargs):
            events.append(args)

    orch = Orchestrator(_cfg(), repo=str(repo),
                        out=lambda *_a, **_k: None)
    orch.journal = _Journal()
    orch._register_native_convergence_seeds()
    seeds = getattr(orch, "_convergence_seeds", None)
    assert seeds and "transient.txt" in seeds, seeds
    assert any(a[0] == "native_convergence_seeds" for a in events)

    # harness precedence: an existing dict is never overwritten
    orch._convergence_seeds = {"harness.txt": "harness"}
    orch._register_native_convergence_seeds()
    assert orch._convergence_seeds == {"harness.txt": "harness"}

    # the PLAN branch: with a history plan present (built from the same
    # rebase state), the registrar reuses its universe — same seeds, no
    # second walk
    orch2 = Orchestrator(_cfg(), repo=str(repo), out=lambda *_a, **_k: None)
    orch2.journal = _Journal()
    orch2._history_plan = None
    orch2._lazy_build_history_from_rebase_state()
    assert orch2._history_plan is not None, "fixture must yield a plan"
    # pin the plan-reuse claim: with a plan present, the registrar must NOT
    # re-walk the range (the lazy build already paid the patch-id walk)
    import unittest.mock as _mock
    with _mock.patch.object(
            GitBackend, "replayed_commit_sequence",
            side_effect=AssertionError("second walk")):
        orch2._register_native_convergence_seeds()
    seeds2 = getattr(orch2, "_convergence_seeds", None)
    assert seeds2 == seeds, (seeds2, seeds)   # identical via either branch


def _cfg():
    from capybase.config import Config
    cfg = Config()
    cfg.future.enable_convergence_seed = True
    return cfg


def test_invalid_utf8_blobs_are_not_false_convergence(repo):
    """s27-80: blob_at decodes with errors="replace", so two DISTINCT blobs
    differing only in invalid-UTF-8 bytes compared EQUAL as bytes and the
    convergence arm wrote a corrupted replacement-char file as a "decided
    final state". Equality must be OID-based (what the harness does)."""
    repo = Path(repo)
    git(repo, "init", "-q", "-b", "main")
    git(repo, "commit", "-q", "--allow-empty", "-m", "base")
    base = git(repo, "rev-parse", "HEAD").stdout.strip()
    git(repo, "checkout", "-q", "-b", "feat")
    (repo / "f.bin").write_bytes(b"\xff payload\n")
    git(repo, "add", "-A")
    git(repo, "commit", "-q", "-m", "feat: invalid utf8 A")
    feat = git(repo, "rev-parse", "HEAD").stdout.strip()
    git(repo, "checkout", "-q", "main")
    (repo / "f.bin").write_bytes(b"\xfe payload\n")
    git(repo, "add", "-A")
    git(repo, "commit", "-q", "-m", "main: invalid utf8 B")
    main = git(repo, "rev-parse", "HEAD").stdout.strip()

    backend = GitBackend(repo)
    seeds = compute_convergence_seeds(
        backend, target_tip=main, source_tip=feat, merge_base=base)
    assert seeds == {}, seeds   # distinct oids, non-generator name: no arm fires
