"""Comment classification — the hard-coded comment-kind detector.

Part A2 of the deferred-comment-reconciliation MVP. Takes the spans from
:func:`enumerate_comment_spans` and labels each as:

- ``MACHINE`` — build tags, lint suppressions, compiler directives, attributes.
  These are CODE (they affect compilation/tooling), not prose. Non-deferable.
- ``LEGAL`` — license/copyright headers. Never rewritten automatically.
  Non-deferable.
- ``GENERATED`` — codegen markers ("generated file; do not edit"). Non-deferable.
- ``DOCTEST`` — executable doc examples (Python ``>>>`` , Rust ``///`` with
  fenced code blocks). Non-deferable (they run as tests).
- ``DEFERRED`` — everything else (prose, TODO, invariant, local narration).
  This is the bucket the masker hides and the reconciler processes.

Hard-coded regex (no LLM) per the design's §2 table. The classification runs
BEFORE any model involvement — a comment matching a known directive syntax never
depends on an LLM correctly recognizing its importance.
"""

from __future__ import annotations

import re
from dataclasses import dataclass
from enum import Enum


class CommentClass(Enum):
    """The classification of a comment region."""
    MACHINE = "machine"       # build tags, lint suppressions, compiler directives
    LEGAL = "legal"           # license/copyright headers
    GENERATED = "generated"   # codegen markers
    DOCTEST = "doctest"       # executable doc examples
    DEFERRED = "deferred"     # prose, TODO, invariant, local narration


#: Whether a class is non-deferable (preserved verbatim through both passes).
NON_DEFERABLE = frozenset({CommentClass.MACHINE, CommentClass.LEGAL, CommentClass.GENERATED, CommentClass.DOCTEST})


@dataclass(frozen=True)
class ClassifiedComment:
    """One comment region with its classification."""
    start: int               # byte offset (inclusive)
    end: int                 # byte offset (exclusive)
    text: str                # the comment text (text[start:end])
    cls: CommentClass        # the classification


# ---------------------------------------------------------------------------
# MACHINE — build tags, lint suppressions, compiler directives
# ---------------------------------------------------------------------------

#: Rust attributes: ``#[...]`` and ``#![...]`` (inner). These are CODE, not
#: comments — but enumerate_comment_spans doesn't emit them (they're not
#: comment-shaped). However, a ``//noinspection`` in a JetBrains IDE or a
#: ``#pragma`` in C/C++ IS a comment that's machine-significant.
_MACHINE_COMMENT_PATTERNS = [
    re.compile(r"^\s*//\s*(?:noinspection|eslint-disable|ts-ignore|spelling-disable)", re.IGNORECASE),
    re.compile(r"^\s*#\s*pragma\b", re.IGNORECASE),
    re.compile(r"^\s*//\s*noinspection\b", re.IGNORECASE),
    re.compile(r"^\s*#\s*type:\s*ignore", re.IGNORECASE),  # mypy: # type: ignore
    re.compile(r"^\s*//\s*fmt:\s*(?:off|on)", re.IGNORECASE),  # rustfmt control
    re.compile(r"^\s*//\s*clippy:\s*", re.IGNORECASE),
]


# ---------------------------------------------------------------------------
# LEGAL — license/copyright headers
# ---------------------------------------------------------------------------

_LEGAL_PATTERNS = [
    re.compile(r"\b(?:copyright|©|\(c\))\b", re.IGNORECASE),
    re.compile(r"SPDX-License-Identifier:", re.IGNORECASE),
    re.compile(r"\blicensed under\b", re.IGNORECASE),
    re.compile(r"\bApache License\b", re.IGNORECASE),
    re.compile(r"\bMIT License\b", re.IGNORECASE),
    re.compile(r"\bGNU (?:General Public|Lesser) License\b", re.IGNORECASE),
    re.compile(r"\bAll rights reserved\b", re.IGNORECASE),
]


# ---------------------------------------------------------------------------
# GENERATED — codegen markers
# ---------------------------------------------------------------------------

_GENERATED_PATTERNS = [
    re.compile(r"\bdo not edit\b", re.IGNORECASE),
    re.compile(r"\bgenerated\b.*\b(?:by|from|with)\b", re.IGNORECASE),
    re.compile(r"(?:^|\s)@generated\b", re.IGNORECASE),
    re.compile(r"\bcodegen\b", re.IGNORECASE),
    re.compile(r"<auto-generated>", re.IGNORECASE),
]


# ---------------------------------------------------------------------------
# DOCTEST — executable doc examples
# ---------------------------------------------------------------------------

_PYTHON_DOCTEST_PATTERN = re.compile(r"^\s*>>>?\s", re.MULTILINE)
_RUST_DOCTEST_PATTERN = re.compile(r"```\s*(?:rust|no_run|ignore|should_panic)?\s*\n", re.MULTILINE)


def classify_comment(comment_text: str, lang: str | None = None) -> CommentClass:
    """Classify a single comment's text into a :class:`CommentClass`.

    Pure regex — no LLM. Hard-coded language-specific patterns per the design's
    §2 table. The first matching class wins (order: MACHINE → LEGAL → GENERATED
    → DOCTEST → DEFERRED fallback).
    """
    # Strip leading comment markers for cleaner pattern matching.
    stripped = comment_text.lstrip()
    # Remove leading //, /*, #, ///, //!, #= etc.
    for prefix in ("///", "//!", "//", "/*", "*/", "#!", "#=", "#", '"""', "'''", "*"):
        if stripped.startswith(prefix):
            stripped = stripped[len(prefix):].lstrip()
            break

    # MACHINE — directives/suppressions (check first: a #pragma that mentions
    # "copyright" is still MACHINE, not LEGAL).
    for pat in _MACHINE_COMMENT_PATTERNS:
        if pat.search(comment_text):
            return CommentClass.MACHINE

    # LEGAL — license/copyright.
    for pat in _LEGAL_PATTERNS:
        if pat.search(stripped):
            return CommentClass.LEGAL

    # GENERATED — codegen markers.
    for pat in _GENERATED_PATTERNS:
        if pat.search(stripped):
            return CommentClass.GENERATED

    # DOCTEST — executable doc examples.
    if lang in ("python", "py"):
        if _PYTHON_DOCTEST_PATTERN.search(stripped) or _PYTHON_DOCTEST_PATTERN.search(comment_text):
            return CommentClass.DOCTEST
    elif lang in ("rust", "rs"):
        # Rust doc comment (/// or //!) with a fenced code block.
        if (comment_text.strip().startswith("///") or comment_text.strip().startswith("//!")):
            if _RUST_DOCTEST_PATTERN.search(comment_text):
                return CommentClass.DOCTEST

    # DEFERRED — everything else.
    return CommentClass.DEFERRED


def classify_spans(
    spans: list[tuple[int, int, str]],
    text: str,
    lang: str | None = None,
) -> list[ClassifiedComment]:
    """Classify a list of comment spans (from :func:`enumerate_comment_spans`).

    Each span ``(start, end, comment_text)`` is classified independently. Returns
    a list of :class:`ClassifiedComment` in source order.
    """
    return [
        ClassifiedComment(
            start=start, end=end, text=comment_text,
            cls=classify_comment(comment_text, lang),
        )
        for start, end, comment_text in spans
    ]


__all__ = [
    "CommentClass",
    "ClassifiedComment",
    "NON_DEFERABLE",
    "classify_comment",
    "classify_spans",
]
